baseurl: /
markdown: kramdown
permalink: /:year/:month/:day/:title/
timezone: Asia/Shanghai

home: https://www.fudongdong.com/
demo: https://demo.fudongdong.com/
base: https://fudongdong.com
github: https://github.com/yihuaxiang/snippets
edit_path: https://github.com/yihuaxiang/snippets/edit/master
new_path: https://github.com/yihuaxiang/snippets/new/master/snippets
author: 敖武
author_en: yihuaxiang
author_info: <a href="https://www.fudongdong.com">敖武</a>

webrick:
  headers:
    Author: 敖武
    About: https://fudongdong.com

gems:
  - jekyll-seo-tag
#  - jekyll-feed

defaults:
  -
    scope:
      path: "snippets"
      type: "posts"
    values:
      layout: nil
