baseurl: /
markdown: kramdown
permalink: /:year/:month/:day/:title/
timezone: Asia/Shanghai

home: http://www.fudongdong.com/
demo: http://demo.fudongdong.com/
base: http://snippets.fudongdong.com
edit_path: https://github.com/fudongdong/snippets/edit/gh-pages
new_path: https://github.com/fudongdong/snippets/new/gh-pages/snippets
author: 敖武
author_en: yihuaxiang
author_info: <a href="http://www.fudongdong.com">敖武</a>

webrick:
  headers:
    Author: 敖武
    About: http://fudongdong.com/about/

gems:
  - jekyll-seo-tag
#  - jekyll-feed

defaults:
  -
    scope:
      path: "snippets"
      type: "posts"
    values:
      layout: nil
